version: '3'
services:
  web:
    build:
        context: ./
        dockerfile: web.dockerfile
    container_name: cmaxs-server
    volumes:
      - ./cmaxs:/var/www/html
    ports:
      - "80:80"
    links:
      - db
  db:
    image: mysql:5.7
    container_name: cmaxs-db
    environment:
      - "MYSQL_ROOT_PASSWORD=rikkei"
      - "MYSQL_DATABASE=cmaxs"
    ports:
      - "3406:3306"
